-- ============================================================
-- Datos de ejemplo para la demostracion (importar DESPUES de database.sql)
-- Contenido ficticio: sirve para probar el portal y el panel.
--
-- Cuentas de demostracion (cambia las claves despues de la evaluacion):
--   admin@dialogoydesarrollo.com.pe      / Admin#2026Demo      (rol admin)
--   redactor@dialogoydesarrollo.com.pe   / Redactor#2026Demo   (rol redactor)
-- ============================================================

SET NAMES utf8mb4;

INSERT INTO usuarios (id, nombres, ap_paterno, ap_materno, email, password_hash, rol) VALUES
(1, 'Administrador', 'Demo', NULL, 'admin@dialogoydesarrollo.com.pe', '$6$ddpAdmin2026x$VsRaLQ9.4kD9zr8Iy6DEjlqVX/LOJoQxnz58OgHWHCjDT4zY/39myFjkI9abN1Caa3Tp7X4EhzH4Jep9anjHA.', 'admin'),
(2, 'Redactor', 'Demo', NULL, 'redactor@dialogoydesarrollo.com.pe', '$6$ddpRedact2026$YR7p5uRC3ogH9WP8pz7gpwdp8bARMt5N7g13w1rMF3NcyNhiv/HVUzy6xY7mAfsxAoUni8xgRK1Qepgm/9U0O1', 'redactor');

INSERT INTO autores (id, nombres, ap_paterno, ap_materno, nickname, es_nickname) VALUES
(1, 'Redacción', 'DDP', NULL, NULL, 0),
(2, 'María', 'Quispe', 'Huamán', NULL, 0),
(3, 'Luis', 'Condori', NULL, 'El Cronista', 1);

INSERT INTO reportajes (id, titulo, resumen_corto, desarrollo, foto_principal, pdf_adjunto, fecha_publicacion, es_destacado, autor_id, usuario_id) VALUES
(1, 'Cómo funciona una mesa de diálogo: actores, reglas y acuerdos', 'Un recorrido por las etapas de una mesa de diálogo, desde la convocatoria hasta el seguimiento de los acuerdos.', '<p>Una mesa de diálogo reúne a actores con intereses distintos para conversar con reglas claras. Su éxito depende de que todos participen con información suficiente y de que los acuerdos queden por escrito.</p><p>Las mesas que funcionan definen desde el inicio quién convoca, quién modera, qué temas se tratan y cómo se hará el seguimiento. Sin esos elementos, el diálogo se convierte en una reunión más.</p><p>Este es un reportaje de ejemplo incluido para probar la publicación del portal.</p>', 'repo.jpg', NULL, '2026-09-17', 1, 1, 1),
(2, 'Cinco claves para prevenir conflictos sociales desde el territorio', 'La prevención empieza con información oportuna, presencia institucional y canales de comunicación abiertos.', '<p>Prevenir un conflicto es más barato y más humano que gestionarlo cuando ya escaló. La alerta temprana requiere escuchar al territorio de manera constante.</p><p>Entre las claves suelen destacar la información accesible, la presencia del Estado, el respeto a las autoridades locales, la transparencia y el seguimiento de compromisos.</p><p>Contenido de ejemplo para la demostración del sitio.</p>', 'repo.jpg', NULL, '2026-09-08', 0, 2, 2),
(3, 'Transparencia y datos abiertos: por qué importan a las comunidades', 'Cuando la información pública es clara y fácil de encontrar, la ciudadanía puede vigilar mejor el uso de los recursos.', '<p>Los datos abiertos permiten que cualquier persona revise cómo se planifican y ejecutan los recursos públicos. Con esa información, las comunidades dialogan en mejores condiciones.</p><p>La transparencia no es solo publicar cifras: implica explicarlas en un lenguaje comprensible y actualizarlas con regularidad.</p><p>Contenido de ejemplo para la demostración del sitio.</p>', 'repo.jpg', NULL, '2026-08-28', 0, 3, 1),
(4, 'El rol de los jóvenes en la vigilancia ciudadana', 'Cada vez más jóvenes participan en el seguimiento de obras y decisiones públicas usando herramientas digitales.', '<p>La vigilancia ciudadana se fortalece con nuevas generaciones que dominan las herramientas digitales y buscan participar en los asuntos de su localidad.</p><p>Los colectivos juveniles registran avances de obras, comparten información y proponen mejoras a las autoridades.</p><p>Contenido de ejemplo para la demostración del sitio.</p>', 'repo.jpg', NULL, '2026-08-18', 0, 1, 2),
(5, 'Agua y desarrollo: experiencias de gestión comunitaria', 'Las juntas de agua muestran cómo la organización local puede sostener servicios básicos en el tiempo.', '<p>En muchas zonas rurales, las juntas administradoras cuidan el agua, cobran cuotas y hacen el mantenimiento de los sistemas.</p><p>Su fortaleza está en el conocimiento del territorio; su reto, contar con apoyo técnico y financiero constante.</p><p>Contenido de ejemplo para la demostración del sitio.</p>', 'repo.jpg', NULL, '2026-08-12', 0, 2, 1),
(6, 'Consulta previa: qué es y cómo se aplica', 'Una explicación sencilla de este derecho de los pueblos indígenas y de las etapas de su implementación.', '<p>La consulta previa es un proceso de diálogo intercultural entre el Estado y los pueblos indígenas antes de adoptar medidas que puedan afectar sus derechos colectivos.</p><p>Suele organizarse en etapas: identificación de la medida, información, evaluación interna, diálogo y decisión.</p><p>Contenido de ejemplo para la demostración del sitio.</p>', 'repo.jpg', NULL, '2026-08-05', 0, 3, 2),
(7, 'Minería y desarrollo local: preguntas para el debate', 'Un conjunto de preguntas que ayudan a discutir cómo los ingresos de una actividad se convierten en obras y servicios.', '<p>Hablar de desarrollo local exige mirar qué recursos llegan a los territorios, cómo se gastan y qué resultados generan en la calidad de vida.</p><p>Este texto de ejemplo propone preguntas para orientar la conversación entre autoridades, empresas y ciudadanía.</p><p>Contenido de ejemplo para la demostración del sitio.</p>', 'repo.jpg', NULL, '2026-07-29', 0, 1, 1),
(8, 'Mujeres líderes en procesos de diálogo', 'Su participación amplía las agendas y mejora la sostenibilidad de los acuerdos.', '<p>Cuando las mujeres participan en las mesas de diálogo, aparecen temas que antes quedaban fuera: cuidado, salud, educación y seguridad.</p><p>Fortalecer su liderazgo requiere espacios seguros, formación y reconocimiento de su trabajo comunitario.</p><p>Contenido de ejemplo para la demostración del sitio.</p>', 'repo.jpg', NULL, '2026-07-20', 0, 2, 2);
